spring:
  application:
    name: productms

  kafka:
    producer:
      bootstrap-server: localhost:9092,localhost:9094
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JacksonJsonSerializer
      acks: all
      properties:
        delivery:
          timeout:
            ms: 120000
        linger:
          ms: 0
        request:
          timeout:
            ms: 30000
#      retries: 10
#      properties:
#        retry:
#          backoff:
#            ms: 1000



