spring:
  application:
    name: emailnotification

  kafka:
    consumer:
      bootstrap-servers: localhost:9092,localhost:9094
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.springframework.kafka.support.serializer.JacksonJsonSerializer
      group-id: product-created-events
      properties:
        spring:
          json:
            trusted:
              packages: com.grazielleanaia.core

server:
  port: 8081