spring:
  application:
    name: emailnotification
  datasource:
    username: user
    password:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
  kafka:
    consumer:
      bootstrap-servers: localhost:9092,localhost:9094
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.springframework.kafka.support.serializer.JacksonJsonSerializer
      group-id: product-created-event-group
      properties:
        spring:
          json:
            trusted:
              packages: com.grazielleanaia.core

server:
  port: 8081