spring:
  application:
    name: depositms

  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: amount-deposit-event-group
      isolation-level: READ_COMMITTED
      properties:
        spring:
          json:
            trusted:
              packages: com.grazielleanaia.core.*

server:
  port: 8083

